### ISSUE TITLE
Specific Book Won't Download

### ISSUE THREAD

**Issue by jacobfiala** [rmcrackan/Libation#1116]
**Describe the bug**

This specific book won't download, but no issues with any other books
https://www.audible.com/pd/The-New-Huey-P-Newton-Reader-Audiobook/B07WSRNDXP

Error Pop-Up:
An error occurred while trying to process this book.
Title: The New Huey P. Newton Reader
ID: B07WSRNDXP
Author: Huey P. Newton, David Hilliard - editor,
Donald...
Narr: Ryan Vincent Anderson, Larry Herron, Joniece Ab...
- ABORT: Stop processing books.
- RETRY: retry this book later. Just skip it for now.
Continue processing books. (Will try this book again later.)
- IGNORE: Permanently ignore this book. Continue processing books. (Will not try this book again later.)
See Settings to avoid this box in the future.

I've retried several times, but the error happens immediately upon starting the download.

**To Reproduce**

1. Go to 'Liberate'
2. Click on 'Liberate Visible Books: 1'
3. Almost Immediately, the error pops up

I've tried changing around some of the settings under "Audio File Settings", but this didn't change anything.

**Expected behavior**

For other books, they all download just fine. 

<img width="337" alt="Screenshot 2025-01-13 at 5 11 56 PM" src="https://github.com/user-attachments/assets/470d887f-8921-415d-a0b2-470d70d502ae" />

**Platform**
macOS 15.2; Macbook Air M1

**Log Files**
Attach your Libation log file here.

[_Log202501.zip](https://github.com/user-attachments/files/18402714/_Log202501.zip)

**Comment by rmcrackan** [comment]
Sorry about this. Thank you very much for your log. I fixed a bit of code around this issue but I haven't fully released the change yet. Can you please try this pre-release and let me know whether it fixes your issue -- https://github.com/rmcrackan/Libation/releases/tag/v11.6.4

**Comment by jacobfiala** [comment]
This did not fix the issue, and furthermore, I now get this error upon opening the app and my library is no longer listed on the left. 
<img width="352" alt="image" src="https://github.com/user-attachments/assets/0a9617dc-acb1-49de-890c-fcfb5f374a9e" />

Scanning the library does not return the list either. But the "liberate" command still works for placing the undownloaded ones into the queue.

<img width="713" alt="image" src="https://github.com/user-attachments/assets/ab98a70c-f205-40cc-bc75-9dd4aa7ffba8" />

But of course, they are still not downloading

**Comment by rmcrackan** [comment]
Can you attach your new log?

**Comment by jacobfiala** [comment]
_Log202501.zip

**Comment by jacobfiala** [comment]
[_Log202501.zip](https://github.com/user-attachments/files/18430279/_Log202501.zip)

**Comment by rmcrackan** [comment]
Thank you very much for the log.

There are a few parts here which you might want to play with. I'd try these tests on one book at a time, one settings-change at a time to see what's breaking. If other things work the maybe we can isolate what combination is breaking on your system.

* it might be something about the mp3 quality in your settings. Try setting this higher or lower
* you're downloading as file-per-chapter. Try as single-file
* you're saving as mp3. Try as the default m4b (that is: uncheck the mp3 option)

I'm leaving town for a few days and I'll available for replies when I return.

@Mbucari Is this just an issue with a too-low sample rate?

Line 1596 from the log above (in their reply on Jan 15. 2 entries above this comment):

```
 {}2025-01-15 14:23:07.108 -05:00 [ERR] (at Dinah.Core.StepRunner.AsyncBaseStep+<RunAsync>d__2.MoveNext()) End step 'Step 2: Download Decrypted Audiobook'. FAILED. Completed in 00:00:00
System.AggregateException: One or more errors occurred. (Unsupported Sample Rate 7350 (Parameter 'format'))
 ---> System.ArgumentException: Unsupported Sample Rate 7350 (Parameter 'format')
   at NAudio.Lame.LameMP3FileWriter..ctor(Stream outStream, WaveFormat format, LameConfig config) in /home/runner/work/AAXClean.Codecs/AAXClean.Codecs/src/NAudio.Lame/LameMP3FileWriter.cs:line 150
```

**Comment by Mbucari** [comment]
@rmcrackan Yes, that is the issue. The MP# lib only supports `8000 Hz <= sample rates <= 48000 Hz`. The `AAXClean.SampleRate` enum has values ranging from 7350 to 96000 because those are [all possible values](https://wiki.multimedia.cx/index.php/MPEG-4_Audio#Sampling_Frequencies) for an mp4 file, but the options in libation's MP3 settings will need to be restricted. I'll push a fix for it shortly.  BTW, is there a reason that the current release is 11.1? There have been a lot of bug fixes since then.

@jacobfiala If you go to Libation's Audio File Settings and change "Max audio sample rate" to 8000, this should work.

**Comment by jacobfiala** [comment]
That worked! Still getting the bad filter string error when I open it, but it works fine anyway!

**Comment by Mbucari** [comment]
@jacobfiala You probably have a corrupted QuickFilters.json file. Try deleting it (which will remove all quick filters you have set) and recreating  your filters.

**Comment by jacobfiala** [comment]
Yep! That was it. I'm back running perfectly. Thank y'all so much!

**Comment by rmcrackan** [comment]
Thank you @Mbucari !!!

> is there a reason that the current release is 11.1? There have been a lot of bug fixes since then.

Fear. I actually did a full release a while back and too many users had issues with it so I deleted it. Every time I believe I've got it ironed out, someone on a pre-release will find something new. I just need to bite the bullet eventually. I'm not ready to though until I can have a lot of free time just in case there's a flood of bug reports after a new full release. And free time has not been abundant lately, so it's easy to put off.

**Comment by Mbucari** [comment]
@rmcrackan 
>I'm not ready to though until I can have a lot of free time just in case there's a flood of bug reports after a new full release. 

When you're thinking of doing it, let me know ahead of time so we can coordinate a schedule where I can help find and fix bugs.

**Comment by rmcrackan** [comment]
> When you're thinking of doing it, let me know ahead of time so we can coordinate a schedule where I can help find and fix bugs.

That would be very cool! I didn't know you were still interested. Would you prefer this week or next? Or other?

**Comment by Mbucari** [comment]
> That would be very cool! I didn't know you were still interested. Would you prefer this week or next? Or other?

The first week in February works better for me. You game for then?

**Comment by rmcrackan** [comment]
> The first week in February works better for me. You game for then?

Sweet -- I added a calendar reminder.
