### ISSUE TITLE
Add user setting to NOT import podcasts.

### ISSUE THREAD

**Issue by Mbucari** [rmcrackan/Libation#125]
I don't want to back up podcasts. Really, I don't want them in Libation at all.  But every time I sync my library, I have to manually remove them again. Can you add a setting for Libation to not import episode types?

**Comment by rmcrackan** [comment]
Good point. I'll look into this.

**Comment by rmcrackan** [comment]
Cheers! This is esp. in appreciation for how quickly you added the new non-DRM stuff -- [v6.1.2](https://github.com/rmcrackan/Libation/releases/latest)

**Comment by Mbucari** [comment]
Thanks!

**Comment by Mbucari** [comment]
It doesn't seem to work.  In fact, at no point during the library scan process is Configuration.DownloadEpisodes ever read.

**Comment by rmcrackan** [comment]
It's in `GetValidLibraryBooks` . I see -- I missed the parans. I'll fix it tonight.

**Comment by rmcrackan** [comment]
Fixed. And actually tested this time :blush: Turns out when you think you can get away with a quick fix and not test, it comes back to bit you every time.

**Comment by Mbucari** [comment]
> Turns out when you think you can get away with a quick fix and not test, it comes back to bit you every time.

So, soooo true...

**Comment by Mbucari** [comment]
OK, so this still isn't working the way I had expected it to, and I think we had a misunderstanding. Libation will skip processing episodes if DownloadEpisodes is unchecked, but the library importer will still import them.  What I wanted was a feature that will skip importing them in the first place. Should skipping importing them into the library be a new and different feature, or can we repurpose DownloadEpisodes to do that?

**Comment by rmcrackan** [comment]
You’re right, I misunderstood the request. I can make that change this week. It will be another bool. Settings will get a little area for episodes like there is for decrypt

**Comment by rmcrackan** [comment]
New setting added to https://github.com/rmcrackan/Libation/releases/tag/v6.1.4
