### ISSUE TITLE
Can't import podcasts from audible.in

### ISSUE THREAD

**Issue by adamgilli** [rmcrackan/Libation#152]
Hello, audible.in recently introduced audible plus. But when i add podcasts to my library and click scan library, it says processed 20, new 20 but none of the episodes are getting imported. I've checked the setting and both import episodes and download episodes are checked. But i can download audiobooks which are part of the plus calalog without any issues. I've attached the log file if it's required. 
[Log202111.log](https://github.com/rmcrackan/Libation/files/7493829/Log202111.log)
.

**Comment by rmcrackan** [comment]
Thank you for the logs. Can you give me an example of a podcast which doesn't work for you? Looking at the logs, I'm seeing errors in v6.4.1 due to a bug which was fixed in 6.4.2 (sorry about that!). After 6.4.2 though, the only errors I see are login, not download.

**Comment by adamgilli** [comment]
> Thank you for the logs. Can you give me an example of a podcast which doesn't work for you? Looking at the logs, I'm seeing errors in v6.4.1 due to a bug which was fixed in 6.4.2 (sorry about that!). After 6.4.2 though, the only errors I see are login, not download.

https://www.audible.in/ep/podcasts
None of the podcasts from the above link can be imported. 
If you need a specific example, you can try this one
https://www.audible.in/pd/Darmiyaan-Podcast/B09HL7S7KY

**Comment by rmcrackan** [comment]
Thank you, That info is perfect.

It sounds like there's a way to add these free ones to your account. If this is the case, I don't think I have a path forward since there's no way for me to test this. I don't have an India account and the US doesn't have an equivalent.

**Comment by thomasalley** [comment]
Hi there! I just found this project this morning and I'm seeing the same thing in the US region. The specific free podcast I'm trying to download is Meltdown, found here:
https://www.audible.com/pd/Episode-1-The-Big-Heist-Podcast/B09J6Z8FTL

I've added it to my Library, and it shows up when I go to view my library. Libation, however, doesn't see it. No errors in the logs.

**Comment by rmcrackan** [comment]
@thomasalley Thanks! I didn't know the US had these. I'll have to investigate.

**Comment by rmcrackan** [comment]
Thanks again everyone for your help. Issue should be fixed in [v6.4.3](https://github.com/rmcrackan/Libation/releases/latest)

**Comment by thomasalley** [comment]
Awesome, thank you! Just confirmed by pulling down an ep of the "podcast" and uploading it to Overcast, seems to work great. Appreciate it!

**Comment by adamgilli** [comment]
Thanks for the update. But still the issue remains the same, at least for audible.in. I'll attach the logs for your reference. 
[Log202111.log](https://github.com/rmcrackan/Libation/files/7510334/Log202111.log)

**Comment by rmcrackan** [comment]
How strange. Please set your logging level to debug, try the import again, and send me the new log.

Settings: Logging level = Debug. Save

After we solve this mystery you can set this level back to Information so the logs don't get ridiculous.

**Comment by adamgilli** [comment]
Thanks for the guidance. I've attached the new logs now after setting the logging level to debug.
[Log202111.log](https://github.com/rmcrackan/Libation/files/7513962/Log202111.log)

**Comment by rmcrackan** [comment]
Thanks.

Your logs show you finding all episodes. Then sometime during the attempt to load them into the database, they just ... don't. I found "Darmiyaan" in the US marketplace and it worked fine for me. Either (1) something is corrupted in your database or (2) audible really did do something different in the India marketplace.

If (1) you can try deleting your database and see if it works on the next scan. The database is the file in the same folder as your logs which is called "LibationContext.db". Just delete that file then restart Libation.

If (2) there's not much I can do because there's no way to debug on my computer. In theory you could email me the file with your tokens but these are the keys to your account. With those someone could do anything they wanted with your account as if they were you. Which also means if anything goes wrong in the future, you'd have every reason to suspect me. That's not a responsibility I'm ready for.

Lacking any path forward I'm going to close this. Sorry I'm not able to solve your problem :(

**Comment by adamgilli** [comment]
Clearing LibationContext.db fixed the problem! Thank you so much :)

**Comment by rmcrackan** [comment]
That's great news! Thanks for the follow up.
