### ISSUE TITLE
Podcast is processed/scanned when I try to import but it doesn't get imported.

### ISSUE THREAD

**Issue by ijsnow15** [rmcrackan/Libation#231]
Signed in to my Amazon UK account and I tried to import a new audible original podcast from my library into Libation. It's able to scan/process all 6 episodes but they do not get added to Libation itself.

**It says**
Total Processed: 6
New: 0

and nothing is added into Libation.

I'm running 6.7.6 and I've tried removing my account and adding it again multiple times but to no avail.

Thanks!

**Comment by rmcrackan** [comment]
Possibly an issue in settings. In your Settings on the "Import library" tab, which boxes are checked?

**Comment by ijsnow15** [comment]
> Possibly an issue in settings. In your Settings on the "Import library" tab, which boxes are checked?

I have all boxes ticked (assuming that I should)

I've tried unchecking each one of them and all of them at the same time but that still didn't work. 

Here are my logs:
[Log202204_001.log](https://github.com/rmcrackan/Libation/files/8493382/Log202204_001.log)
[Log202204_002.log](https://github.com/rmcrackan/Libation/files/8493383/Log202204_002.log)
[Log202204.log](https://github.com/rmcrackan/Libation/files/8493384/Log202204.log)

**Comment by rmcrackan** [comment]
First of all, much thanks for running this in debug (actually verbose) mode and providing the logs. That just saved us a lot of time.

I can see from your logs that Libation sees thet podcast but then doesn't recognize it as something with episodes. In the US site, that podcast imports fine. Audible must be doing something different on the UK site but I don't have an active UK account so I can't debug this locally.

In the folder where your Libation files are, back up `AudibleUtilities.dll`. Download and upzip [this zip file](https://github.com/rmcrackan/Libation/files/8496032/AudibleUtilities.zip) and put its files into that folder (which will overwrite the old AudibleUtilities.dll file). Run a new scan. This will output all details of your library to `library.json`. I recommend [emailing](https://github.com/rmcrackan) that to me rather than posting it here. It won't contain personally identifiable info, but it will list your full library.

**Comment by ijsnow15** [comment]
I replaced `AudibleUtilities.dll` and now it gives me this: **Fatal error, pre-logging** dialog box when I open libation andsays this:

```
Could not load file or assembly 'FileManager, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

   at LibationFileManager.Configuration.get_LibationFiles()
   at LibationFileManager.Configuration.get_SettingsFilePath() in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\LibationFileManager\Configuration.cs:line 62
   at LibationFileManager.Configuration.get_LibationSettingsAreValid() in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\LibationFileManager\Configuration.cs:line 20
   at LibationWinForms.Program.RunInstaller(Configuration config) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\LibationWinForms\Program.cs:line 84
   at LibationWinForms.Program.Main() in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\LibationWinForms\Program.cs:line 41
```

I tried to find the log for this but I couldn't. I'm also not sure where `library.json` is. Should I just re-download Libation?

I'm not sure what I'm doing wrong, I haven't used a Windows in years and only opened this 7-year old laptop after a long time. So it could be a problem caused by my laptop? I'm also not techy, so my apologies and thank you for trying to help!

**Comment by rmcrackan** [comment]
My apologies -- that's on me. That's what I get for trying to take shortcuts.

[Here's a full version](https://www.dropbox.com/s/0jw4yt03durq92l/TestBuild.zip?dl=0) with my new logging hack. When you run this version, it will experience the same issue with which you opened this issue, and it will also dump your library's details into a file called library.json.

**Comment by ijsnow15** [comment]
Just emailed you the .json file.

Thank you!

**Comment by rmcrackan** [comment]
Thanks for those files. All info is retrieved correctly from audible and all 6 successfully get to the step for adding to the database. Then it's exiting that step with 0 new items instead of 6. As though they're already in the database. Let's rebuild the database and search engine. Maybe in one of those is something's stuck in a bad way and that's why it won't re-add.

* Open the folder with your logs
* Close Libation
* Delete `LibationContext.db` -- this is your database
* Delete folder `SearchEngine`
* Restart Libation
* Do a new scan

Let me know if it's any different this time

**Comment by ijsnow15** [comment]
I tried scanning and it actually said 6 new ones this time, but I clicked ok but they still aren't visible and it seems they didn't get imported, so I scanned again, then it's back to processing all 6 of them but I'm getting 0 new.

log attached

[Log202204_003.log](https://github.com/rmcrackan/Libation/files/8497899/Log202204_003.log)

**Comment by rmcrackan** [comment]
wtf. Can you zip and email me your database file?

**Comment by ijsnow15** [comment]
Sent!

**Comment by rmcrackan** [comment]
Please ignore the 'closed' issue -- github "helpfully" does this automatically when I create a bug fix for a specific issue, whether or not I want it to.

I think I've got it fixed now. Crossing my fingers!

* Delete your database file and search engine folder again
* Download [latest](https://github.com/rmcrackan/Libation/releases/latest)
* This time the scan should work like normal

Let me know if your issue persists.

You've been awesome by the way. I couldn't have asked for more.

**Comment by ijsnow15** [comment]
I'm sorry, it still won't work after I followed your steps. Now it says error importing library.

I tried removing my account, deleting the database file again (the search engine folder wasn't there anymore), re-opened libation, and signed in again. That error shows up everytime I try to import.

Attached log. I'm sorry if this has been a pain!
[Log202204_003.log](https://github.com/rmcrackan/Libation/files/8498230/Log202204_003.log)

**Comment by rmcrackan** [comment]
Here we go again. Back up the files in this zip. Overwrite with the new ones. Kill the database and search engine. Restart Libation. Scan. And have a whiskey. Wait, that last one is just for me.

[DtoImporterService.zip](https://github.com/rmcrackan/Libation/files/8499057/DtoImporterService.zip)

**Comment by rmcrackan** [comment]
If this works, I'll do another real release. I don't want to keep pinging users with update notices until this is fully fixed though.

**Comment by ijsnow15** [comment]
It still does not work, and I feel terrible. The 6 episodes gets scanned the first try, but they don't get imported. I scan again, all 6 gets processed, but it's back to 0 new.

Perhaps this is a "me problem" with my computer? I appreciate all the help you've given and this is such a wonderful project, but I don't want to waste your time.

[Log202204_004.log](https://github.com/rmcrackan/Libation/files/8499206/Log202204_004.log)

**Comment by rmcrackan** [comment]
I'll follow up in email. My next suggestion is not for mass consumption
