### ISSUE TITLE
Update to 8.6 fails

### ISSUE THREAD

**Issue by CharlieRussel** [rmcrackan/Libation#403]
**Describe the bug**
Update from 8.5.1.1 (classic) fails. 

**To Reproduce**
Started Libation, got the prompt for an update, said yes, let Libation finish opening, and finish downloading 8.6, then closed Libation. When it restarted, it prompted me again. Rinse, repeat
**Expected behavior**
Update

**OS:** Windows 11

**Log Files**
Attach your Libation log file here.
[Log202212.log](https://github.com/rmcrackan/Libation/files/10173040/Log202212.log)

**Comment by rmcrackan** [comment]
Eek!! Apologies. I'm not sure what went wrong. I deleted this release. Please go back to 8.5.1 for now. I'm so sorry

**Comment by rmcrackan** [comment]
@Mbucari I remember that too. Everything in Dinah and AudibleApi solutions are .net7 and their dependencies are up to date. Libation runs fine in debug and release. Even running publish from VS works. I'll keep poking around it today

**Comment by CharlieRussel** [comment]
I got a notice about 8.6.2, but it doesn't appear to actually be available?  Que paso?

**Comment by rmcrackan** [comment]
I'm still debugging. That one didn't work either so I deleted it

**Comment by CharlieRussel** [comment]
If I manually download and run 8.6.3.1, it appears to work fine. But it isn't triggering an automatic update if I start 8.5.1.1.

**Comment by Mbucari** [comment]
@rmcrackan You tried doing a manual clean of all projec files? Delete \bin and \obj for every Libation library?

**Comment by rmcrackan** [comment]
Should be fixed now, including using the new yaml builds

**Comment by CharlieRussel** [comment]
Sorry, @rmcrackan, it still fails the auto-update. :( 

System: Windows 11
Libation location: D:\Libation
Previous version: 8.5.1.1
Libation: Classic Libation

When run manually from a different location, 8.6.4.1, it appears to run as expected.

**Comment by rmcrackan** [comment]
It looks like there's something wrong with the autoupater in 8.6.4. Possibly it doesn't work with .net7. It downloads and unzips but doesn't update the files. Look inside your Libation folder and you'll see a new folder inside where 8.6.4 was downloaded

I deleted the 8.6.4 release and tried to get a local 8.5.1 to update to 8.6.3 to see if that has the same issue. I may have exceeded my attempts for the hour or the day because I'm unable to do so. I'll do some testing with the autoupdater library and .net7 when I get some spare time. I spent a ton of work time on this today so I need to get back to my actual job for a bit.

**Comment by CharlieRussel** [comment]
@rmcrackan -- From a different computer, on 8.5.0.1, I started Libation and it finally prompted for the update and installed it. For some reason it was **really** slow. First to bring up the prompt, and then to finish the install. But it finally did what it needed to do and the upgrade went well. I'll test on the more usual machine, a Surface Book 2, later today.
