### ISSUE TITLE
LoadSessionCookiesAsync exceeded maximum attempts.

### ISSUE THREAD

**Issue by weirdalsuperfan** [rmcrackan/Libation#78]
I had some trouble with my password, but by the time I was able to fix it it seems I had used all my login attempts. I can log in via my browser just fine, but I can't get Libation to log into my account. I've attempted to log in through Libation multiple times but I keep getting this error. It's been less than 24 hours since I first got it, so I don't know if it'll fix itself if I just wait, but anyway before I forget I figure I'll post this here...basically it seems I'm locked out from attempting to log in too many times.

> 2021-08-02 17:32:43.775 redacted (at InternalUtilities.AudibleApiActions.GetApiAsync(AudibleApi.ILoginCallback, InternalUtilities.Account)) GetApiAsync. {"Account":"AccountId=redac[...]ted@re[...]da.ct[...]ed|AccountName=redac[...]ted|Locale=redacted","LocaleName":"redacted"}
2021-08-02 17:32:56.286 redacted (at LibationWinForms.Login.WinformResponder.showDialog(System.Windows.Forms.Form)) {"DialogResult":"OK"}
2021-08-02 17:32:57.141 redacted (at ApplicationServices.LibraryCommands+<ImportAccountAsync>d__0.MoveNext()) Error importing library
System.TimeoutException: Authenticate.LoadSessionCookiesAsync exceeded maximum attempts. MaxLoadSessionCookiesTrips=6
   at AudibleApi.Authentication.Authenticate.LoadSessionCookiesAsync() in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Authentication\Authenticate.cs:line 74
   at AudibleApi.Authentication.Authenticate.SubmitCredentialsAsync(String email, String password) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Authentication\Authenticate.cs:line 81
   at AudibleApi.Authentication.Authenticate.SubmitCredentialsAsync(Locale locale, String email, String password) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Authentication\Authenticate.cs:line 55
   at AudibleApi.EzApiCreator.loginAsync(Locale locale, ILoginCallback responder) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\EzApiCreator\EzApiCreator.cs:line 65
   at AudibleApi.EzApiCreator.GetApiAsync(Locale locale, String identityFilePath, String jsonPath, ILoginCallback loginCallback) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\EzApiCreator\EzApiCreator.cs:line 47
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func\`2 loginCallbackFactoryFunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\LibraryCommands.cs:line 77
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func\`2 loginCallbackFactoryFunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\LibraryCommands.cs:line 31
2021-08-02 17:32:57.188 redacted (at LibationWinForms.MessageBoxAlertAdmin.Show(System.String, System.String, System.Exception)) Alert admin error: {"text":"Error importing library. Please try again. If this still happens after 2 or 3 tries, stop and contact administrator","caption":"Error importing library"}
System.TimeoutException: Authenticate.LoadSessionCookiesAsync exceeded maximum attempts. MaxLoadSessionCookiesTrips=6
   at AudibleApi.Authentication.Authenticate.LoadSessionCookiesAsync() in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Authentication\Authenticate.cs:line 74
   at AudibleApi.Authentication.Authenticate.SubmitCredentialsAsync(String email, String password) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Authentication\Authenticate.cs:line 81
   at AudibleApi.Authentication.Authenticate.SubmitCredentialsAsync(Locale locale, String email, String password) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Authentication\Authenticate.cs:line 55
   at AudibleApi.EzApiCreator.loginAsync(Locale locale, ILoginCallback responder) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\EzApiCreator\EzApiCreator.cs:line 65
   at AudibleApi.EzApiCreator.GetApiAsync(Locale locale, String identityFilePath, String jsonPath, ILoginCallback loginCallback) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\EzApiCreator\EzApiCreator.cs:line 47
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func\`2 loginCallbackFactoryFunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\LibraryCommands.cs:line 77
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func\`2 loginCallbackFactoryFunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\LibraryCommands.cs:line 31
   at LibationWinForms.Dialogs.IndexLibraryDialog.IndexLibraryDialog_Shown(Object sender, EventArgs e) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\LibationWinForms\Dialogs\IndexLibraryDialog.cs:line 34
   
   I'm not sure what C:\Dropbox\DinahsFolder is (I can't find it on my computer), but anyway I stop Dropbox before attempting to use Libation.

**Comment by rmcrackan** [comment]
Thanks for the logs. I’ll be unavailable for about 2 weeks and will look at this when I return

**Comment by weirdalsuperfan** [comment]
Follow up (not sure if directly related). I'm able to get past the password entry and captcha entry forms, but after entering my 2FA I get this error instead now:

> Could not register

>   at AudibleApi.Authorization.Authorize.RegisterAsync(AccessToken accessToken, IEnumerable\`1 cookies) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Authorization\Authorize.cs:line 81
   at AudibleApi.Authorization.IdentityMaintainer.RegisterAsync() in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Authorization\IdentityMaintainer.cs:line 103
   at AudibleApi.Authorization.IdentityMaintainer.CreateAsync(IIdentity identity, IAuthorize authorize, ISystemDateTime systemDateTime) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Authorization\IdentityMaintainer.cs:line 38
   at AudibleApi.Authorization.IdentityMaintainer.CreateAsync(IIdentity identity) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\Authorization\IdentityMaintainer.cs:line 31
   at AudibleApi.EzApiCreator.createApiAsync(IIdentity identity) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\EzApiCreator\EzApiCreator.cs:line 130
   at AudibleApi.EzApiCreator.GetApiAsync(Locale locale, String identityFilePath, String jsonPath, ILoginCallback loginCallback) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\audible api\AudibleApi\AudibleApi\EzApiCreator\EzApiCreator.cs:line 50
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func\`2 loginCallbackFactoryFunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\LibraryCommands.cs:line 77
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func\`2 loginCallbackFactoryFunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\ApplicationServices\LibraryCommands.cs:line 31
   at LibationWinForms.Dialogs.IndexLibraryDialog.IndexLibraryDialog_Shown(Object sender, EventArgs e) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\LibationWinForms\Dialogs\IndexLibraryDialog.cs:line 34
   
I've tried some simple stuff like closing Dropbox and turning off my VPN, but the result is the same. Btw I have 2 different accounts across 2 different regions (I'm currently in the region for this account, which isn't working - I've already successfully added my other one).

**Comment by rmcrackan** [comment]
Fixed here: https://github.com/rmcrackan/Libation/releases/tag/v5.4.9

**Comment by weirdalsuperfan** [comment]
That update fixed a different issue I didn't know I had until I tried resynching my first account today. Only problem is, I still get the same "Could not register" error for my second account after upgrading and deleting everything from DownloadsInProgress. This second account I can't register is in Japan btw. Not sure if their API is different or something.

**Comment by rmcrackan** [comment]
> Japan

Japan and Australia seem to be doing something slightly different. I'll see if I can figure out what
